name: Build and deploy SR to Azure Web App

on:
  push:
    branches:
      - main
  pull:
    branches:
      - main

jobs:
  build:
    name: Build frontend and load backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Build frontend
        run: |
          cd frontend
          npm install 
          npm run build
          cd ..
      - name: Load backend
        run: |
          cd backend
          npm install
          cd ..
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: SR-BE-PROD
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: SR-BE-PROD

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'synapse-recommendations'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_110380CBFF0149D8B8B3BC59B6A000E6 }}
          package: .
